name: claire-hamilton-website
region: nyc

# API Service (Backend - Express API)
services:
  - name: api
    github:
      repo: AntonyNeal/sw_website
      branch: main
    source_dir: /api
    build_command: npm install
    run_command: node server.js
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${DATABASE_URL}
      - key: DB_HOST
        scope: RUN_TIME
        value: ${DB_HOST}
      - key: DB_PORT
        scope: RUN_TIME
        value: ${DB_PORT}
      - key: DB_NAME
        scope: RUN_TIME
        value: ${DB_NAME}
      - key: DB_USER
        scope: RUN_TIME
        value: ${DB_USER}
      - key: DB_PASSWORD
        scope: RUN_TIME
        value: ${DB_PASSWORD}
      - key: DB_SSL
        scope: RUN_TIME
        value: require
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
    routes:
      - path: /api

  # Web Service (Frontend - Static Site served via http-server)
  - name: frontend
    github:
      repo: AntonyNeal/sw_website
      branch: main
    build_command: npm install && npm run build
    run_command: npm run start
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: VITE_GA_MEASUREMENT_ID
        value: ${GA_MEASUREMENT_ID}
      - key: VITE_API_BASE_URL
        value: https://octopus-app-s8m2n.ondigitalocean.app/api
      - key: VITE_FUNCTIONS_URL
        value: ${FUNCTIONS_URL}
    routes:
      - path: /

# Domain configuration
domains:
  - domain: clairehamilton.com
    type: PRIMARY
  - domain: www.clairehamilton.com
    type: ALIAS
  - domain: clairehamilton.vip
    type: ALIAS
